-- Drop tables if they exist to start fresh
DROP TABLE IF EXISTS lessons;
DROP TABLE IF EXISTS sections;

-- Sections Table
CREATE TABLE sections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number integer NOT NULL UNIQUE,
    name text NOT NULL,
    slug text NOT NULL UNIQUE
);

-- Lessons Table
CREATE TABLE lessons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id bigint REFERENCES sections(id) ON DELETE CASCADE NOT NULL,
    number integer NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    content jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_published boolean DEFAULT false,
    UNIQUE(section_id, number), 
    UNIQUE(section_id, slug)
);

-- Enable RLS
ALTER TABLE sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read
CREATE POLICY "Enable read access for all users" ON sections FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON lessons FOR SELECT USING (true);
